# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '/Users/datduong/Desktop/miniapp'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'home-true-money' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for home-true-money

  # Import Flutter module
  install_all_flutter_pods(flutter_application_path)
  
end




